# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/foundation-sites/scss"
    - "bower_components/motion-ui/src"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    # Libraries requried by Foundation
    - "bower_components/jquery/dist/jquery.js"
    - "bower_components/what-input/what-input.js"
    # Core Foundation files
    - "bower_components/foundation-sites/dist/plugins/foundation.core.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.util.*.js"
    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    - "bower_components/foundation-sites/dist/plugins/foundation.abide.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.accordion.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.accordionMenu.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.drilldown.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.dropdown.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.dropdownMenu.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.equalizer.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.interchange.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.magellan.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.offcanvas.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.orbit.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.responsiveMenu.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.responsiveToggle.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.reveal.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.slider.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.sticky.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.tabs.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.toggler.js"
    - "bower_components/foundation-sites/dist/plugins/foundation.tooltip.js"
    # Paths to your own project code are here
    - "src/assets/js/!(app).js"
    - "src/assets/js/app.js"
